---
- hosts: node1
  become: true
  remote_user:  root
  vars_files:
    - vars.yml
   
  tasks:
  - name: installatioin
    yum:
      name: "{{item}}"
      state:  absent
    with_items: "{{pkg}}"

  - name: remove user
    user:
      name: "{{item}}"
      state:  absent
      remove: yes
    with_items: "{{usr}}"

#  - yum:  name= "{{item}}"  state=  absent
#	  with_items:
#      - "{{pkg}}"

#	- name: remove users
#	  user:
#		  name: "{{item}}"
#		  state: absent
#      remove: yes
#	  with_items: "{{usr}}"

